MSD1 = input("Enter your Birthday")
MSD2 = input("Enter your Birthday")
MSD3 = input("Enter your Birthday")
MSD4 = input("Enter your Birthday")
MSD5 = input("Enter your Birthday")
MSD6 = input("Enter your Birthday")
MSD7 = input("Enter your Birthday")



































print(MSD1 )
print(MSD2 )
print(MSD3 )
print(MSD4 )
print(MSD5 )
print(MSD6 )
print(MSD7 )