Number = 21

while Number == 21

int(input("Enter a number"))


if Number>1<5:
    print ("🥶")

elif 15>Number>6:
    print("🌡️ ")

elif 20>Number>16:
    print("🔥")

elif 30>Number>20:
    print("🌡️ ")

elif 40>Number>30:
    print("🥶")

elif 50>Number>40:
    print("🧊")



if Number>50:
    print("invlsid result")

if Number<1:
    print("invalid result")

else:
    print("invalid result")



































